export const MY_ADDRESS_REQUEST = "MY_ADDRESS_REQUEST";
export const MY_ADDRESS_SUCCESS = "MY_ADDRESS_SUCCESS";
export const MY_ADDRESS_FAIL = "MY_ADDRESS_FAIL";

export const ADDRESS_DETAILS_REQUEST = "ADDRESS_DETAILS_REQUEST";
export const ADDRESS_DETAILS_SUCCESS = "ADDRESS_DETAILS_SUCCESS";
export const ADDRESS_DETAILS_FAIL = "ADDRESS_DETAILS_FAIL";

export const ALL_ADDRESS_REQUEST = "ALL_ADDRESS_REQUEST";
export const ALL_ADDRESS_SUCCESS = "ALL_ADDRESS_SUCCESS";
export const ALL_ADDRESS_FAIL = "ALL_ADDRESS_FAIL";
export const ALL_ADDRESS_OF_REPORT_REQUEST = "ALL_ADDRESS_OF_REPORT_REQUEST";
export const ALL_ADDRESS_OF_REPORT_SUCCESS = "ALL_ADDRESS_OF_REPORT_SUCCESS";
export const ALL_ADDRESS_OF_REPORTS_FAIL = "ALL_ADDRESS_OF_REPORTS_FAIL";

export const NEW_ADDRESS_REQUEST = "NEW_ADDRESS_REQUEST";
export const NEW_ADDRESS_SUCCESS = "NEW_ADDRESS_SUCCESS";
export const NEW_ADDRESS_FAIL = "NEW_ADDRESS_FAIL";
export const NEW_ADDRESS_RESET = "NEW_ADDRESS_RESET";

export const DELETE_ADDRESS_REQUEST = "DELETE_ADDRESS_REQUEST";
export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";
export const DELETE_ADDRESS_FAIL = "DELETE_ADDRESS_FAIL";
export const DELETE_ADDRESS_RESET = "DELETE_ADDRESS_RESET";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAIL = "UPDATE_ADDRESS_FAIL";
export const UPDATE_ADDRESS_RESET = "UPDATE_ADDRESS_RESET";

export const MONTH_OF_ADDRESS_REQUEST = "MONTH_OF_ADDRESS_REQUEST";
export const MONTH_OF_ADDRESS_SUCCESS = "MONTH_OF_ADDRESS_SUCCESS";
export const MONTH_OF_ADDRESS_FAIL = "MONTH_OF_ADDRESS_FAIL";

export const YEAR_OF_ADDRESS_REQUEST = "YEAR_OF_ADDRESS_REQUEST";
export const YEAR_OF_ADDRESS_SUCCESS = "YEAR_OF_ADDRESS_SUCCESS";
export const YEAR_OF_ADDRESS_FAIL = "YEAR_OF_ADDRESS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
