export const GET_ALL_MONTH_REQUEST = "GET_ALL_MONTH_REQUEST";
export const GET_ALL_MONTH_SUCCESS = "GET_ALL_MONTH_SUCCESS";
export const GET_ALL_MONTH_FAIL = "GET_ALL_MONTH_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
