export const ADD_PAYMENT_REQUEST = "ADD_PAYMENT_REQUEST";
export const ADD_PAYMENT_SUCCESS = "ADD_PAYMENT_SUCCESS";
export const ADD_PAYMENT_FAIL = "ADD_PAYMENT_FAIL";
export const ADD_PAYMENT_RESET = "ADD_PAYMENT_RESET";

export const ALL_PAYMENT_REQUEST = "ALL_PAYMENT_REQUEST";
export const ALL_PAYMENT_SUCCESS = "ALL_PAYMENT_SUCCESS";
export const ALL_PAYMENT_FAIL = "ALL_PAYMENT_FAIL";

export const PAYMEN_DETAILS_REQUEST = "PAYMEN_DETAILS_REQUEST";
export const PAYMEN_DETAILS_SUCCESS = "PAYMEN_DETAILS_SUCCESS";
export const PAYMEN_DETAILS_FAIL = "PAYMEN_DETAILS_FAIL";

export const UPDATE_PAYMENT_REQUEST = "UPDATE_PAYMENT_REQUEST";
export const UPDATE_PAYMENT_SUCCESS = "UPDATE_PAYMENT_SUCCESS";
export const UPDATE_PAYMENT_RESET = "UPDATE_PAYMENT_RESET";
export const UPDATE_PAYMENT_FAIL = "UPDATE_PAYMENT_FAIL";

export const DELETE_PAYMENT_REQUEST = "DELETE_PAYMENT_REQUEST";
export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";
export const DELETE_PAYMENT_FAIL = "DELETE_PAYMENT_FAIL";
export const DELETE_PAYMENT_RESET = "DELETE_PAYMENT_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
