export const ADD_YEAR_REQUEST = "ADD_YEAR_REQUEST";
export const ADD_YEAR_SUCCESS = "ADD_YEAR_SUCCESS";
export const ADD_YEAR_FAIL = "ADD_YEAR_FAIL";
export const ADD_YEAR_RESET = "ADD_YEAR_RESET";

export const GET_ALL_YEAR_REQUEST = "GET_ALL_YEAR_REQUEST";
export const GET_ALL_YEAR_SUCCESS = "GET_ALL_YEAR_SUCCESS";
export const GET_ALL_YEAR_FAIL = "GET_ALL_YEAR_FAIL";

export const GET_YEAR_DETAIL_REQUEST = "GET_YEAR_DETAIL_REQUEST";
export const GET_YEAR_DETAILV_SUCCESS = "GET_YEAR_DETAILV_SUCCESS";
export const GET_YEAR_DETAIL_FAIL = "GET_YEAR_DETAIL_FAIL";

export const GET_YEAR_Of_ADDRESS_DETAIL_REQUEST =
  "GET_YEAR_Of_ADDRESS_DETAIL_REQUEST";
export const GET_YEAR_Of_ADDRESS__SUCCESS = "GET_YEAR_Of_ADDRESS__SUCCESS";
export const GET_YEAR_Of_ADDRESS__FAIL = "GET_YEAR_Of_ADDRESS__FAIL";

export const GET_ORDER_Of_YEAR_REQUEST = "GET_ORDER_Of_YEAR_REQUEST";
export const GET_ORDER_Of_YEAR_SUCCESS = "GET_ORDER_Of_YEAR_SUCCESS";
export const GET_ORDER_Of_YEAR_FAIL = "GET_ORDER_Of_YEAR_FAIL";

export const DELETE_YEAR_REQUEST = "DELETE_YEAR_REQUEST";
export const DELETE_YEAR_SUCCESS = "DELETE_YEAR_SUCCESS";
export const DELETE_YEAR_FAIL = "DELETE_YEAR_FAIL";
export const DELETE_YEAR_RESET = "DELETE_YEAR_RESET";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
